# Generated by Django 5.2 on 2025-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='defaults/white gal.jpg', null=True, upload_to='Avatars/'),
        ),
    ]
