# Generated by Django 5.2 on 2025-07-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_room_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='room_imgs/')),
                ('vid_mus', models.FileField(upload_to='room_vids_musics/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.room')),
            ],
        ),
    ]
