# Generated by Django 5.2 on 2025-07-10 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='vid_mus',
            new_name='vid',
        ),
        migrations.AddField(
            model_name='content',
            name='mus',
            field=models.FileField(default=django.utils.timezone.now, upload_to='room_musics/'),
            preserve_default=False,
        ),
    ]
