# Generated by Django 5.2 on 2025-07-29 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_joinedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='vid',
            field=models.FileField(upload_to='room_vids/'),
        ),
    ]
