# Generated by Django 5.2 on 2025-08-20 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_content_time_stamp_alter_content_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedrooms',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
